### ISSUE TITLE
created_at and updated_at standards

### ISSUE THREAD

**Issue by LimeBlast** [fuel/oil#10]
According to what I've seen from the migration files created by oil when running the scaffold command, the standard for created_at and updated_at fields are that of signed int for storing unix timestamps.

The issue I can see with this is that the maximum a MySQL database can store in an signed int is 2147483647 - which equals Tue, 19 Jan 2038 03:14:07 GMT. While this is indeed many years in the future, would it not be better to have the default set at unsigned int, allowing for a value of 4294967295 - or Sun, 07 Feb 2106 06:28:15 GMT, or even bigint (either signed or unsigned), for even further dates into the future?

**Comment by crynobone** [comment]
Wouldn't it be better to use DATETIME or TIMESTAMP?

**Comment by philsturgeon** [comment]
No point switching from unix to mysql and hating our lives right now just to stop a potential issue thats outside of the lifetime of the majority of applications, but making unsigned is fine by me. 

TheWorldOfDan: if you'd like to make this change i'll be happy to merge it. Makes sense to me!
