### ISSUE TITLE
DOCROOT constant doesn't point to the same location as public/index.php

### ISSUE THREAD

**Issue by crynobone** [fuel/oil#101]
> You rejoined the room.
> [11:36am] crynobone: WanWizard: got a minute?
> [12:10pm] WanWizard: crynobone: whats up?
> [12:11pm] crynobone: is there any reason why DOCROOT in oil and public/index.php doesn't point to the same folder
> [12:11pm] WanWizard: don't know
> [12:11pm] crynobone: can we make it the same? 
> [12:12pm] WanWizard: in both cases it points to the directory the script is in. don't know what happens if you change it
> [12:12pm] WanWizard: try it out 
> [12:13pm] crynobone: yeah
> [12:13pm] crynobone: or should we add another constant
> [12:13pm] crynobone: ie WEBROOT?
> [12:14pm] crynobone: it would be easier if for instance oil want to lookup file in assets folder, or other related stuff
> [12:16pm] crynobone: had a scenario where i need it before, but forgotten
> [12:19pm] WanWizard: crynobone: DOCROOT is used only once in oil, for loading phpunit. that might be done differently, in which case it would be save to alter DOCROOT
> [12:19pm] WanWizard: create an issue for it so Phil can have a look
> [12:19pm] crynobone: ok

This introduce an inconsistent result when running from oil (cli) and public/index.php (web) when you try to include custom feature. 
## Scenario

In my case, I was trying to use a simplified config.php file inside public/ folder for db configuration (this would be useful to create a web-app style deployment). 

```
<?php

// Load in the Autoloader
require COREPATH.'classes'.DIRECTORY_SEPARATOR.'autoloader.php';
class_alias('Fuel\\Core\\Autoloader', 'Autoloader');

// Bootstrap the framework DO NOT edit this
require COREPATH.'bootstrap.php';


Autoloader::add_classes(array(
    // Add classes you want to override here
    // Example: 'View' => APPPATH.'classes/view.php',
    'Controller' => APPPATH.'classes/controller.php',
));

// Register the autoloader
Autoloader::register();

if ( ! is_file(DOCROOT.'config.php'))
{
    throw new \HttpNotFoundException();
}
else
{
    include DOCROOT.'config.php';
}
```
## Excepted Behavior

Running from web and cli would work without any problem. 
## Actual Result

oil failed to run anything because DOCROOT return different path.

**Comment by mikebranderhorst** [comment]
I agree with the confusion, sinds the DOCROOT is moved from base.php it is sometimes confused to have two different DOCROOTS (one in app and one in oil). The main reason - although it is save to do - why I do not change the DOCROOT in oil is that you never know if a package or addon or whatever relies on it and thus break.

**Comment by WanWizard** [comment]
Response: https://github.com/fuel/fuel/commit/d2a997b592b5472145f2ff392e31f63ace62d07c#commitcomment-1012988

**Comment by frankdejonge** [comment]
The DOCROOT points to the directory the executing code resides in. So this in concept differs between index.php and oil. Other constants like APPPATH are always in the same place. Changing this will affect BC badly.
