### ISSUE TITLE
Generate Scaffold based on Database

### ISSUE THREAD

**Issue by dbpolito** [fuel/oil#103]
Would be great if we have a way to generate scaffold based on created database tables instead of create it all from oil then we can use a DB Design Tool.

oil g scaffold users --from-table (get the fields on users table and generate the files)

Does it make sense for someone else?

**Comment by WanWizard** [comment]
At the moment that would only be possible for MySQL, as the current database layer does not support the required functionality for other platforms.

Having said that, +1 :)

**Comment by codeho** [comment]
yep, my +1 stands here as well :)

**Comment by Erocanti** [comment]
+1

**Comment by WanWizard** [comment]
It should be possible to implement now, as the PDO driver now has list_columns() implemented.

**Comment by frankdejonge** [comment]
I'd say, code it up and request a pull :)

**Comment by dbpolito** [comment]
Great... i'm going to start working on it. :D

**Comment by douglao** [comment]
+1

**Comment by evanrolfe** [comment]
+2

**Comment by kenjis** [comment]
There is an implementation of my friend.

See https://github.com/mp-php/fuel-myapp/blob/master/tasks/scafdb.php

**Comment by WanWizard** [comment]
To be usable it would need an ORM implementation too. And it needs a check to see if list_columns() doesn't throw exceptions and returns something useful.

**Comment by mamor** [comment]
This task is calling the standard method of FuelPHP.
https://github.com/fuel/oil/issues/103#issuecomment-10261672

Model_Crud will be generated if '--crud' option is given.
ORM is generated if no option is given.

Since some corrections were made, please see.
https://github.com/mp-php/fuel-myapp/blob/master/tasks/scafdb.php

**Comment by mamor** [comment]
Thank you :)
