### ISSUE TITLE
Oil not working under cPanel cron

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/oil#107]
The Oil package not working under cPanel cron jobs.

It throws an exception:

ErrorException [ Error ]: Class 'Fuel\Core\Exception' not found

The exception it want to throw:
Cli class cannot be used outside of the command line.

I edited the oil package and removed any lines that contains anything abot Cli class, and now it works under cPanel.

I think cPanel runs cron jobs another way or I don't know the problem, but it is not working under cPanel.

**Comment by frankdejonge** [comment]
Since Oil is the Command Line Interface, it would be illogical to not have it work with Cli. So this is an issue with cPanel, not Oil.
