### ISSUE TITLE
env parameter doesn't affect configs loaded in config.php

### ISSUE THREAD

**Issue by rob-mccann** [fuel/oil#115]
If you have the following in config.php 
`'config' => array('session'),`
and run 
`php oil r migrate --env=production`

it will load the development config/session.php or config/development/session.php rather than the one in config/production/session.php

This appears to because environment gets set after fuel has loaded the default configs.

Not sure if this should be fixed for how it would be.

**Comment by WanWizard** [comment]
-- cut --

**Comment by WanWizard** [comment]
Sorry, made a stupid comment.

Yes, at the moment that doesn't work. The environment is set and Fuel init is called from the App bootstrap, which is run before the Oil package is loaded and commandline parameters can be interpreted.

**Comment by WanWizard** [comment]
Proposed solution: dump the --env switch, as it is interpreted too late in the process, and switch to the way Ruby does it:

```
FUEL_ENV=staging php oil <commands>
```
