### ISSUE TITLE
Feature request: Subdirs for tasks

### ISSUE THREAD

**Issue by mikebranderhorst** [fuel/oil#116]
`php oil refine update/lang` or `php oil refine update_lang`

I like the second method best. `update_lang:method` almost looks like `Update_lang::method()`

task: `tasks/update/lang.php`

class: `oil/classes/refine.php`

line 61: `if ( ! $file = \Finder::search('tasks', str_replace('_', '/', $task)))`

line 88: `$task = '\\Fuel\\Tasks\\'.ucfirst(str_replace('/', '_', $task));`

**Comment by WanWizard** [comment]
@philsturgeon comments?

**Comment by philsturgeon** [comment]
Check the robots example:

http://d.pr/i/xQEo

This is already done.

**Comment by mikebranderhorst** [comment]
Robots example is without subdir, I mean:

`php oil r robots_protect:humans`

`php oil r robots/protect:humans`

`tasks/robots/protect.php` with method `humans`

**Comment by philsturgeon** [comment]
Why?

**Comment by mikebranderhorst** [comment]
Few reasons:
1) the ability to have a collection of tasks as a git repo which you can share among projects
2) I keep on having huge task files and to split I have to break apart the task file in several include files, having subdirs like controller etc. has is easier to maintain and visual nicer
3) group tasks not only on one level but two levels or more
4) instead of using `updateLanguage:nl "general"` use: `update/language:nl "general"`, this way all update tasks are in one folder and language has its own task file `update/language.php` etc.

I know you can use `public function language($language, $filename)` but I have a huge update task file and it would be nice to split but keep as group update. This is just an example...
