### ISSUE TITLE
Template.php missing in the views folder

### ISSUE THREAD

**Issue by altrim** [fuel/oil#117]
When trying to generate admin section it tries to open the file template.php (/oil/views/admin/orm/views/template.php) but it is missing it's not in the folder.

**Comment by WanWizard** [comment]
Is your code up to date? This has been fixed on Apr 06, 2012.

**Comment by altrim** [comment]
Yes I also tried a fresh install and it's the same issue. When I run the oil g admin command the error raises. Also as I can see here the file isn't located where the script is looking in /oil/view/admin/orm/views/. 
Then I just copy pasted the file (template.php) that I have from an older installation in the directory  and it works.

**Comment by altrim** [comment]
I think I found the issue. It's in the generate/admin.php class in the source array. I saw the commits and @philsturgeon fixed that but when you download the app there is still the old source ($subfolder.'/views/template.php').

**Comment by WanWizard** [comment]
How do you download? If you clone the repo, be sure to install and update all submodules, their reference might not be updated.

**Comment by altrim** [comment]
Through curl,oil as it's in the documentation or from the website.

**Comment by WanWizard** [comment]
That does a `git clone` of the default branch in the fuel/fuel repository. 

If that repository hasn't been updated after an update of a submodule, you're not installing the latest version of the submodule. This is the way submodules work, they always point to a specific commit hash, you can't reference HEAD to always get the latest version.
