### ISSUE TITLE
Cannot migrate consistently between environments.

### ISSUE THREAD

**Issue by acairns** [fuel/oil#118]
From a clean DB, running a few simple test migrations:

```
php oil r migrate --env=test --all
```

Result:

```
Already on the latest migration for app:default.
Performed migrations for package:argh:
001_blah1
002_blah2
003_blah3
004_blah4
005_blah5
006_blah6
007_blah7
008_blah8
```

Followed by:

```
php oil r migrate --all
```

Result:

```
Already on the latest migration for app:default.
Already on the latest migration for package:argh.
```

Expected behaviour: migrate up the other database specified in the db config.
I do have both my database configs setup correctly - this issue has only just recently started to occur.

If I delete my migrations.php config file each time, I seam to get more reliable results.
But then, migrating up/down when switching env's from here gets really inconsistent results.

I'm not too sure what's going on or how/if multiple environments are managed with the single migrations config file.

**Comment by WanWizard** [comment]
I've just commiited a patch that will save migration config files to the environment folder, instead of keeping them globally. 

So after you move your current config/migrations.php file to the correct environment folder (the one that contains the database that is migrated using that config), per-environment migrations should be supported.

Could you verify that and give me some feedback?

**Comment by acairns** [comment]
Thanks for looking into this mate.

```
$ php oil r migrate --all
Already on the latest migration for app:default.
Error - Invalid basepath, cannot update a file at this location. in COREPATH/classes/file.php on line 297
```

Whole app is 777'ed - looking into this now to see if I can see the problem
Debugging the basepath looks to be trying to save something in /app/config/development/development/

**Comment by WanWizard** [comment]
Hmm... bug is elsewhere, just a sec...

**Comment by WanWizard** [comment]
Fixed, turned out to be an issue in the File_Area class.

**Comment by acairns** [comment]
Yeah, retested this also and looks good.
Thanks for your time on this mate, its quite important to our teams workflow!
Much appreciated!

**Comment by WanWizard** [comment]
no problems, just in time for the 1.2 release ;)
