### ISSUE TITLE
generate controller to subdirectory

### ISSUE THREAD

**Issue by eoconnell** [fuel/oil#119]
I realize this is not currently the intention of the command but I think it would be a nice addition.

`oil generate controller admin/test action1 action2`  

will create a controller in `classes/controllers/admin` and views in `views/admin/test`.

Currently it creates the appropriate files in the proper directory structure, but it names the controller `Controller_Admin/test` instead of `Controller_Admin_Test` which breaks the routing.

**Comment by WanWizard** [comment]
This has been implemented in 1.5/develop.
