### ISSUE TITLE
"oil r migrate" duplicates package status in config migrations.php

### ISSUE THREAD

**Issue by kenjis** [fuel/oil#120]
Every time I run "oil r migrate", entries of package in migrations.php increases.

``` php
        'package' => 
        array(
            'sentry' => 
            array(
                0 => '001_install_sentry_auth',
                1 => '002_add_group_parent_column',
                2 => '001_install_sentry_auth',
                3 => '002_add_group_parent_column',
                4 => '001_install_sentry_auth',
                5 => '002_add_group_parent_column',
            ),
        ),
```

**Comment by WanWizard** [comment]
I can not reproduce that here. 

I've just added a package with migrations to a test app, and it migrates just fine. Are you on 1.2 code? And if so, do you perhaps have a migrations.php file in both app/config and app/config/&lt;environment> ?

**Comment by kenjis** [comment]
I'm sorry, you're right.

I had both app/config/migrations.php and app/config/development/migrations.php.
I deleted app/config/migrations.ph, it does not be reproduced.
