### ISSUE TITLE
Upgrade bootstrap twitter 1.4 to 2.0.3

### ISSUE THREAD

**Issue by ghost** [fuel/oil#124]
i'm interested in to upgrade default admin and scaffolding template from bootstrap twitter 1.4 to 2.0.3. I think we need to upgrade both https://github.com/fuel/fuel and https://github.com/fuel/oil too. What people think about that ?

**Comment by stalmok** [comment]
+1

**Comment by davidhemphill** [comment]
+1

**Comment by WanWizard** [comment]
Bootstrap has been updated to 2.0.3. in the Fuel main repo on May 23, 2012.
