### ISSUE TITLE
Scaffolding uses out-of-date Bootstrap CSS selectors

### ISSUE THREAD

**Issue by docrpm** [fuel/oil#136]
It's a very minor issue, but I noticed recently that the view code generated by **oil g scaffold ...** appears to use out-of-date class selectors for some of the bootstrap CSS. For example, it seems that the button class names in Fuel (e.g., "btn primary") have changed in bootstrap to "btn btn-primary." I'm fairly certain I am running FuelPHP 1.2.1, so hopefully should have the most recent version of oil and Fuel classes.

Anyway, thanks for the great stuff!

**Comment by WanWizard** [comment]
Doesn't seem to be backported to 1.2.1, it is correct in 1.3/develop. I'm pretty sure you can just copy the views over to get it working again.

**Comment by docrpm** [comment]
Thanks...I'll take a look.
