### ISSUE TITLE
Twitter Bootstrap css not complete - Oil generated admin navbar not styled

### ISSUE THREAD

**Issue by loopdream** [fuel/oil#138]
Just followed the tutorial by Phil Sturgeon on how to build and Admin panel with FuelPHP (net.tuts)
All good except when creating the Admin scaffold with oil the resuting admin navbar isnt being styled properly.
Looks like the bootstrap css for this element is missing in the codebase

**Comment by WanWizard** [comment]
There was a discrepancy between the CSS and the oil template updates around the time of the last release.

This has been fixed in 1.3/develop, but not backported to a 1.2 release version yet.  You might want to try installing 1.3/develop instead.
