### ISSUE TITLE
Add support for relations on generate

### ISSUE THREAD

**Issue by dbpolito** [fuel/oil#147]
Oil would be even awesome if it supports generating models with relations, if this is useful to someone else i can code it up! :D

// Creating the Relations Separately
    php oil g model user name:varchar[50] status:char[1] --no-timestamp
    php oil g model category title:varchar[50] status:char[1] --no-timestamp

```
php oil g model post user_id:[belongs_to:user] category_id:[belongs_to:category] title:varchar[50] body:text --no-timestamp
```

// Creating the Relations on the fly. We can also add a has_many automatically on Category and User Model

```
php oil g model post user_id:[belongs_to:user name:varchar[50] status:char[1] --no-timestamp] category_id:[belongs_to:category title:varchar[50] status:char[1] --no-timestamp] title:varchar[50] body:text --no-timestamp
```

// Beauty Way

```
php oil g model post \
    user_id:[ \
        belongs_to:user \
            group_id:[ \
                belongs_to:group \
                    name:varchar[50] \
                    status:char[1] \
                --no-timestamp \
            ] \
            name:varchar[50] \
            status:char[1] \
        --no-timestamp \
    ] \
    category_id:[ \
        belongs_to:category \
            title:varchar[50] \
            status:char[1] \
        --no-timestamp \
    ] \
    title:varchar[50] \
    body:text \
--no-timestamp
```

Let me know your thoughts.

**Comment by diegomosela** [comment]
+1

**Comment by douglao** [comment]
+1

**Comment by WanWizard** [comment]
I wonder how much time you would save by trying to type that on the commandline, vs just creating the models...

**Comment by WanWizard** [comment]
@FrenkyNet I propose to close this, I don't think it will add something, it means a lot of extra parsing code, and no real benefit. Agreed?

**Comment by frankdejonge** [comment]
@WanWizard indeed, this can get real messy, real soon, all pain, no gain as far as I can see.
