### ISSUE TITLE
Typo in PKGPATH/oil/classes/generate/scaffold.php

### ISSUE THREAD

**Issue by evanrolfe** [fuel/oil#155]
Running oil generate scaffold gives the following error:

Notice - Undefined index: plural_name in PKGPATH/oil/classes/generate/scaffold.php on line 105

I changed that line from:

``` php
$data['plural_name'] = \Cli::option('singular')? $data['singular_name'] : \Inflector::pluralize($data['plural_name']);
```

TO:

``` php
$data['plural_name'] = \Cli::option('singular')? $data['singular_name'] : \Inflector::pluralize($data['singular_name']);
```

Which seems to work, looks like it is just a typo.

**Comment by WanWizard** [comment]
Has been fixed. I'll update the zipfile
