### ISSUE TITLE
DOCROOT overridden by Oil - new constant for public dir?

### ISSUE THREAD

**Issue by Altreus** [fuel/oil#158]
When running oil tasks `DOCROOT` is defined using `__DIR__`. Apparently we've had this discussion and it's because `DOCROOT` now defines the base of the Fuel installation, which is quite reasonably assumed to be where oil is.

Trouble is, now there's a discrepancy between the web version and the CLI version.

Would a new constant, e.g. `PUBROOT`, be appropriate, to permanently be defined by the app's bootstrap or config or suchlike to always point to the place the public directory is? That way we don't have to rely on `DOCROOT/public` (for example) for architectures like ours where Fuel is installed in a subdirectory of the site root and the public folder is not a subdirectory of `DOCROOT` at all.

**Comment by WanWizard** [comment]
This has been discussed in the past. We don't see the need for new or more contants. The Oil script is, like the index.php script, part of your application installation, so you can change it how you see fit.
