### ISSUE TITLE
Can't install oil on Ubuntu Natty

### ISSUE THREAD

**Issue by gmedel** [fuel/oil#16]
Followed the instructions posted on the site.
$ curl get.fuelphp.com/oil | sh

When I try to create a new project I get the following:

$ oil create project
/usr/bin/oil: line 8: git: command not found
Could not open input file: ./project/oil

And if I run:
$oil
I get:
This is not a valid Fuel installation so Oil is a bit lost.
        http://fuelphp.com/docs/installation/instructions.html

Didn't find any documentation about it.... What am I doing wrong?

**Comment by crynobone** [comment]
Have you install git for Linux first? `/usr/bin/oil: line 8: git: command not found`

**Comment by gmedel** [comment]
I feel like an idiot... hahahaha
Thank you so much crynobone
