### ISSUE TITLE
Oil command for Module Generation

### ISSUE THREAD

**Issue by CitizenOfRome** [fuel/oil#160]
Has there been any progress with the module generation feature discussed at http://fuelphp.com/forums/discussion/455/oil-generate-module ?

> php oil generate module < modulename >

**Comment by WanWizard** [comment]
No, oil generation has had a low priority, and since the structure is going to change in 2.0, it's no point addressing this now.

**Comment by sagikazarmark** [comment]
I have implemented package generation for myself. Should I push it here? It includes different types of packages (driver-based classes, single classes, etc) I know this issue is about modules, but it is similar.

**Comment by WanWizard** [comment]
Sounds like a plan. Create a PM so we can have a look.

**Comment by frankdejonge** [comment]
PM => PR ;)

**Comment by WanWizard** [comment]
"note to self: :coffee: before github"...

**Comment by sagikazarmark** [comment]
PR #213 sent

**Comment by WanWizard** [comment]
PR was merged.
