### ISSUE TITLE
Oil SimpleAuth argument

### ISSUE THREAD

**Issue by chris-roerig** [fuel/oil#161]
It would be nice to auto create the users table through Oil with a command such as:

oil generate migration simpleauth

**Comment by WanWizard** [comment]
The reason for it not being there is that any database operation, including this one, should be in a normal migration file. 

I've added it to the Auth package: https://github.com/fuel/auth/commit/fa1efccfe6c84677d1def1e36ffa5037812d3e8d

**Comment by chris-roerig** [comment]
Excellent. Thanks
