### ISSUE TITLE
admin scaffold creates an endless loop in controller

### ISSUE THREAD

**Issue by corbosman** [fuel/oil#173]
If I run:  oil refine fromdb:scaffold domains -a

I get an admin.php controller  that endlessly loops. This is because before() checks if you're logged in, and if not, redirects you to login().  But login() also passes before(), so it redirects again..and again..

**Comment by WanWizard** [comment]
This has been fixed here: https://github.com/fuel/oil/commit/1b334d1160736846fe7a3bdc4e3ca5e9fb1abb16 (in 1.6/develop).
