### ISSUE TITLE
Oil generates empty migrations

### ISSUE THREAD

**Issue by destructivecreator** [fuel/oil#208]
I am using this command to generate a migration:

`oil g migration posts title:varchar[50] --soft-delete`

The result is empty up() and down() methods. The same happens without using the --soft-delete. 

``` php
namespace Fuel\Migrations;

class Posts
{
    public function up()
    {

    }

    public function down()
    {

    }
}
```

PHP 5.4.6-1ubuntu1.3 (cli) (built: Jul 15 2013 18:19:45) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies

Fuel 1.6 Downloaded 3 days ago.

**Comment by WanWizard** [comment]
Your syntax is wrong, so oil doesn't know what to generate, none of the required commands are present.

Assuming you want to create a table called posts, it would be
`oil generate migration create_posts title:varchar[50] --soft-delete`
