### ISSUE TITLE
Database Collation

### ISSUE THREAD

**Issue by InsiteFX** [fuel/oil#210]
I generated tables with oil and it set the collation to utf8_general_ci, I always use utf8_unicode_ci. After looking at the DBUtil code I saw that you can set the database charset to utf8_unicode_ci and this works! but after that I always have to change it back or I start getting invalid charset errors. Can we get a collation setting added to the database configuration or fix this so that the whole database see it correct?

NOTE: If the charset is left at utf8_unicode_ci for the collation the Sessions quit to work! until you set it back to utf8

Thank you

**Comment by WanWizard** [comment]
Related https://github.com/fuel/core/issues/1512

**Comment by WanWizard** [comment]
Fixed in https://github.com/fuel/core/issues/1512
