### ISSUE TITLE
$current_user in scaffold

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/oil#211]
There is reference for $current_user variable in scaffolded views, but the parent controller is Controller_Template and not Controller_Base (like in generated admin), so this variable is never set.

**Comment by WanWizard** [comment]
Which views exactly? A search only reveals the admin template view that uses it.

**Comment by WanWizard** [comment]
@sagikazarmark any feedback? or can this be closed?

**Comment by sagikazarmark** [comment]
oil / views / scaffolding / orm /

There is no base controller, where $current_user could be set. The generated controller extends Controller_Template. But somehow I can't reproduce the issue now.

**Comment by WanWizard** [comment]
Went through every file in that folder (and all underlying folders), no "current_user" to be found...
