### ISSUE TITLE
OIl server detached mode

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/oil#212]
I have a different implementation of oil server. Mine has option to run it detached from the consol and control it with start/stop/restart command by storing the process id in a file.

Shall I push it here? The base code is the same, the start/stop is in a task now.

**Comment by WanWizard** [comment]
What do you mean by "oil server"?

**Comment by sagikazarmark** [comment]
I mean the phpserver created in 1.7/develop.

**Comment by WanWizard** [comment]
that probably doesn't work on Windows? If we include functionality, it should be platform independent.

**Comment by sagikazarmark** [comment]
No, it doesn't, since it uses `kill`, `cat` and `ps` commands.

**Comment by WanWizard** [comment]
Then it's not a good idea to add it.

**Comment by sagikazarmark** [comment]
Ok, I will try to find a way to make it work on Windows.

**Comment by WanWizard** [comment]
I can assume this can be closed, or did the last 15 months give you a brillant idea how to address this? :smiley:

**Comment by sagikazarmark** [comment]
LOL, that windows project. I hated that. Anyway, yes: DON'T USE WINDOWS AND DON'T LET YOUR CLIENTS DO.
