### ISSUE TITLE
Oil admin generate generating wrong links

### ISSUE THREAD

**Issue by InsiteFX** [fuel/oil#230]
Will not run on a live server Linux with Apache but works local
$this->template->content   = View::forge('admin\pages/view', $data);

This works on both Windows local and the live server
$this->template->content   = View::forge('admin/pages/view', $data);

**Comment by InsiteFX** [comment]
I tracked it done to it being this and here is the fix

packages/oil/classes/generate/scaffold.php Lines 85 to 92

// Either foo or folder/foo
$view_path = $controller_path = str_replace(
    array('_', '-'),
    '/',          //DS, change the DS to '/' that fixes the problem, see below same code.
    \Str::lower($controller_name)
);

Not sure if the model one below it will also need to be fixed.

// Models are always singular, tough!
$model_path = str_replace(
    array('_', '-'),
    DS,
    \Str::lower($model_name)
);

**Comment by kenjis** [comment]
You generated files on Windows, and your live server is Linux, right?

`DS` means `\` on Windows, `/` on Linux. PHP for Linux uses only `/` as directory separator, 
but PHP for Windows uses both `/` and `\` as directory separator.

In that case, all `DS` in generated files should be `/`.

**Comment by InsiteFX** [comment]
Correct.

It took me awhile but the fix is above in scaffold.php

It's sending the $view_path to the views directory were there are templates that are used in the controllers.
