### ISSUE TITLE
Adding fields to existing tables does not work as expected.

### ISSUE THREAD

**Issue by m0nocle** [fuel/oil#24]
I tried this:
`oil generate migration add_field_with_underscore_to_table field_with_underscore:type[size]`

This generates the migration code:

``` php


<?php

namespace Fuel\Migrations;

class Add_field_with_underscore_to_table {

    public function up()
    {
    \DBUtil::add_fields('field_with_underscore_to_table', array(
                        'field_with_underscore' => array('constraint' => 0, 'type' => 'type'),

    )); 
    }

    public function down()
    {
    \DBUtil::drop_fields('field_with_underscore_to_table', array(
            'field_with_underscore'    
    ));
    }
}
```

But this works:

`oil generate migration add_table field_with_underscore:[type]`

But this produces nonsensical migration names.

It should ignore everything between `add_` and `table` in `add_field_with_underscore_to_table`, while generating the code.

Right now it doesn't.

**Comment by crynobone** [comment]
This pull https://github.com/fuel/oil/pull/31 should solve the problem

**Comment by m0nocle** [comment]
That works.

**Comment by crynobone** [comment]
Should be able to close this issue
