### ISSUE TITLE
Features missing from the "fromdb" task

### ISSUE THREAD

**Issue by WanWizard** [fuel/oil#244]
The ability to generate proper migrations leaves a bit to be desired at the moment.

Not supported yet:
- primary key detection
- table primary key is hardcoded to "id"
- column default value
- "not null" detection
- secondairy indexes
- created_at gets removed if defined in the target table
- updated_at gets removed if defined in the target table
- generates lowercase in classnames "Create_some_table" instead of "Create_Some_Table" for migrations
- no constraint support for type = decimal
- no unsigned value detection

**Comment by stvowi** [comment]
Are this features realized meanwhile?

**Comment by WanWizard** [comment]
No, not that I'm aware of. This task was a third-party contribution.

I personally never use it, as the RDBMS can never produce all information needed to generate a correct model, so it is quicker to create the model manually, especially once you've made a template.

Some of these might be easy to address, some of them might be difficult. I'll see if I can find a bit of spare time later this week.
