### ISSUE TITLE
oil generate test

### ISSUE THREAD

**Issue by watilde** [fuel/oil#246]
Currently `--with-test` option, it can't create scaffolding for some classes like Model/Controller/View/Presenter  already exists. How about to make it possible to generate test scaffolding?

```
$ oil generate test model:name controller:name view:name presenter:name
```

Thanks.

**Comment by watilde** [comment]
@stevewest @WanWizard Any thoughts on this please?

**Comment by emlynwest** [comment]
I am not sure what you are asking here, you want to generate tests for views and presenters via the scaffolding?

**Comment by watilde** [comment]
Thanks for your quick response! I mean, I'd like to generate some test scaffolding for model(and the others) via like `oil generate test model:model_name`.
