### ISSUE TITLE
Parse error in driver package scaffolding 

### ISSUE THREAD

**Issue by AdamSGit** [fuel/oil#248]
When you use Oil to scaffold a package with driver in 1.8, there is a missing bracket causing a parse error line 50 of the main package class (the line throwing an exception).
Let me know if you want a pull request,
Adam

**Comment by WanWizard** [comment]
Line 50 is a blank line? https://github.com/fuel/oil/blob/1.9/develop/classes/package.php#L50

Or do you mean something else? In that case, yes, a PR on 1.9/develop please, so we can see what you mean.

**Comment by AdamSGit** [comment]
I'm talking about the main package class for a scaffolded package.

If I do `php oil g package test -d=mydriver`, the `/fuel/package/test/test.php` is the concerned file.

**Comment by WanWizard** [comment]
Ok, found it.
