### ISSUE TITLE
Field types decimal and float break model and create incorrect migration

### ISSUE THREAD

**Issue by ljubodrag** [fuel/oil#249]
In version 1.8, the following command results in broken model and incorrect migration (constraint is not saved):
`php oil g model location name:string zip:int lat:decimal[10,8] lng:decimal[11,8]`

However, if we insert quotes around constraints it works as expected. Like this:
`php oil g model location name:string zip:int lat:decimal['10,8'] lng:decimal['11,8']`

The same goes for float field type.

**Comment by WanWizard** [comment]
I tried both with the current codebase (1.9/dev), but the generated model is in both cases exactly the same as it doesn't contain any constraint information, and I don't see any differences in the migration generated too, whether or not you use quotes. Both generate

``` php
    'lat' => array('constraint' => '10,8', 'type' => 'decimal'),
    'lng' => array('constraint' => '11,8', 'type' => 'decimal'),
```

I checked the code for recent changes, but this bit hasn't changed since 2011.

**Comment by ljubodrag** [comment]
I tested this thoroughly and it turned out to be a console issue and not a Fuel issue. 
I use Windows machine for my development. When I ran this command in PowerShell it resulted in the error I described. But when I tried it in Cmd and in GitBash console, it worked perfectly.

I am closing this as an non-issue.

**Comment by WanWizard** [comment]
Ok, so it is Powershell that did some "pre-parsing" of the parameters. It might be worth mentioning that in the docs, in case someone else bumps into it.

**Comment by ljubodrag** [comment]
I just found out that in Powershell commas make arrays (http://www.vistax64.com/powershell/236858-commas-powershell.html)

In the docs, on Oil introduction page, there could be a note for Windows users with recommended console utility (Git Bash - https://git-scm.com/downloads if they use git, which they probably do) or at least a note to avoid Powershell.

**Comment by WanWizard** [comment]
Added a note about this, and your tip, to the `oil generate` docs page.
