### ISSUE TITLE
"fromdb" task

### ISSUE THREAD

**Issue by stvowi** [fuel/oil#250]
php oil refine fromdb:scaffold --all don't work with MYSQL - PDO Driver.
I get a lot of errors.

**Comment by WanWizard** [comment]
Is not supported. 

To be able to generate models from database tables, you need to be able to get all column details. There is no generic PDO interface for that.

If you want to use this, you need to switch to the MySQLi driver.

**Comment by stvowi** [comment]
Okay, please write it in the documentation.

**Comment by WanWizard** [comment]
Good point.
