### ISSUE TITLE
'Unique' misspelled in Generate_Migrations_Actions

### ISSUE THREAD

**Issue by kcapps** [fuel/oil#256]
Line 128:

$unique = $unique['unique'] ? ' UNUQUE' : '';

Causes migrations to fail that have unique indexes.

**Comment by WanWizard** [comment]
Oops... I'll have a look in a minute...

**Comment by WanWizard** [comment]
Pushed as a hotfix. Should be installed automatically on "composer upgrade".

**Comment by kcapps** [comment]
Thank you, sir!
