### ISSUE TITLE
Pagination error when generated from `oil generate admin`

### ISSUE THREAD

**Issue by findrakecil** [fuel/oil#258]
Hello, I got an error about pagination when I tried to generate a page using `oil generate admin`. Here's how I got this error:

- Create a page using oil

`oil generate admin categories name:string`

- Open the page and I got this error

<img width="1552" alt="jepretan layar 2018-12-09 pukul 2 34 23 am" src="https://user-images.githubusercontent.com/3760093/49785801-49adb080-fd54-11e8-92c9-c980e75a9633.png">

After checking the controller for index page, turns out that the `Pagination::forge()` is missing the first argument for the name of the pagination instance

<img width="1552" alt="jepretan layar 2018-12-09 pukul 2 35 08 am" src="https://user-images.githubusercontent.com/3760093/49785947-be80ea80-fd54-11e8-9834-8b3a2e496b62.png">

It should be like this

<img width="1478" alt="jepretan layar 2018-12-11 pukul 3 02 14 pm" src="https://user-images.githubusercontent.com/3760093/49786385-23891000-fd56-11e8-80d2-0854473dce31.png">

I already fixed the issue and I will create a pull request for this issue.

**Comment by WanWizard** [comment]
I have closed the PR, as it does not only contain the fix, but also changes to other parts of the code. 

If those changes are necessary, create a seperate PR for them, explaining why. The current description says "beautifying", but the code also contains logic changes...

**Comment by findrakecil** [comment]
Ah, yes.. I'm sorry. I thought that I could just include the related changes in the same issue.

I will make another PR just for this issue. And other PR for "beautifying" the generated code because I thought that the generated code was "ugly" 😅

**Comment by WanWizard** [comment]
My problem is more that "beautifying" should not include logic changes. And I see for example a changed `action_index()` method without any explanation why...

**Comment by findrakecil** [comment]
Ah, yes.. I'm sorry. Thank you for the guidance. I'll do better next time
