### ISSUE TITLE
Broken link for oil cell

### ISSUE THREAD

**Issue by findrakecil** [fuel/oil#266]
## Summary

Hello, I found a broken link for `oil cell` command documentation

## Process

1. Open file `classes/cell.php`
2. On line 181, try to open the link for documentation

## Current and expected result

When opening that link, it showed a 404 error page.

**Comment by WanWizard** [comment]
Everything related to "cells" need to be removed, it was designed and planned to be a public package store, but it never got off, everyone uses github and/or packagist these days.

**Comment by findrakecil** [comment]
I see.. I will make a PR to remove `cells`. I hope I can make it soon
