### ISSUE TITLE
Exceptions in tasks

### ISSUE THREAD

**Issue by phil-lavin** [fuel/oil#27]
Exceptions in tasks seem to be a little sporadic. For example, I have this line:

$domain->metaphones[] = Model_Metaphone::find_or_create(array('metaphone'=>metaphone($word)));

The assignment was failing because I typoed the related model. This is throwing an exception which can be caught in a try/catch block however, until I did a bunch of die()s to work out where the error line was and surrounded it in a try/catch block with a print of the exception, it failed to notify me of the error.

**Comment by WanWizard** [comment]
Just created this task:

```
<?php
namespace Fuel\Tasks;

class Foo {

    public static function run()
    {
        throw new \Exception('I\'m borked');
    }
}
```

And oil responded with `Error - I'm borked in APPPATH/tasks/foo.php on line 8` so I consider this issue solved.
