### ISSUE TITLE
Controller class names always become singular

### ISSUE THREAD

**Issue by akuzemchak** [fuel/oil#28]
Whenever I generate a controller via Oil that has a plural name, the actual class name ends up using the singular version.

For example, if I type `php oil g controller users index login logout` the class name will end up being `Controller_User` (instead of `Controller_Users`), which will causes an error when trying to load the controller.

After digging around, it seems like the culprit is `$class_name = \Inflector::classify($plural);` which actually singularizes the name in the `classify` function.

One solution (not sure if it's the best one) would be to add a second parameter to the classify function, like so:

``` php
public static function classify($table_name, $force_singular = true)
{
    return preg_replace('/(^|_)(.)/e', "strtoupper('\\1\\2')", ($force_singular) ? static::singularize($table_name) : $table_name);
}
```

Then the Oil function could be called like:

``` php
$class_name = \Inflector::classify($plural, false);
```

**Comment by philsturgeon** [comment]
Looks good to me, could you fire it over as a pull request?

**Comment by akuzemchak** [comment]
Yup, pull requests sent to the two different repos:
- https://github.com/fuel/core/pull/351
- https://github.com/fuel/oil/pull/29
