### ISSUE TITLE
oil g controller creates singular file and controller names

### ISSUE THREAD

**Issue by ghost** [fuel/oil#30]
Using FuelPHP v1.0 Final

When using oil g controller to create a new controller it creates the singular version of the filename and the classname rather than the pluralized one.

Example:
php oil g controller url

Creates:
app/classes/controller/url.php -> class Controller_Url extends ...

Rather than
app/classes/controller/urls.php -> class Controller_Urls extends ...

Relevant lines are in packages/oil/classes/generate/generate.php

44: $filename = trim(str_replace(array('_', '-'), DS, $singular), DS);
52: array_unshift($args, $singular);

**Comment by philsturgeon** [comment]
I'm pretty sure this was fixed in develop, did you check?

**Comment by philsturgeon** [comment]
Oh no, the issue that was fixed was a bug. This is just you doing it wrong!

```
php oil g controller urls
```

**Comment by philsturgeon** [comment]
I've made it so it will accept either. Solved!
