### ISSUE TITLE
Problem with Scaffolding pluralize words ending in 'ory'

### ISSUE THREAD

**Issue by icomefromthenet** [fuel/oil#34]
When generating a scaffold using word like category, the controller file name is pluralized to categories, but the controller name inside the class is not also renamed. 

This causes a 404 error on the controller

**Comment by icomefromthenet** [comment]
maybe on line 60 of oil/scaffold.php use 

$data['controller'] = 'Controller_'.\Inflector::pluralize($full_underscores);

instead of

$data['controller'] = 'Controller_'.\Inflector::classify(\Inflector::pluralize($full_underscores));

**Comment by jschreuder** [comment]
Better fix would be to use [Inflector::classify()'s second param](http://fuelphp.com/dev-docs/classes/inflector.html#method_classify)

**Comment by crynobone** [comment]
I believe this already fixed in latest 1.1/develop.. cc @FrenkyNet @jschreuder

**Comment by frankdejonge** [comment]
This has indeed been fixed by my last commit, last night. https://github.com/fuel/oil/commit/48e7d9105e8d6ee82261cbbef77b6cf0d8c5d7f6 and in one before.
