### ISSUE TITLE
After scaffold wrong model filename

### ISSUE THREAD

**Issue by cbabos** [fuel/oil#36]
Hi there!

I just wrote that command (the problem is repeatable): 
$~: oil g scaffold users firstname:string lastname:string username:string password:char[45] active:tinyint[1]
    Creating model: /var/www/html/fuelLearn/fuel/app/classes/model/users.php
    Creating migration: /var/www/html/fuelLearn/fuel/app/migrations/001_create_users.php
    Creating controller: /var/www/html/fuelLearn/fuel/app/classes/controller/users.php
    Creating view: /var/www/html/fuelLearn/fuel/app/views/users/index.php
    Creating view: /var/www/html/fuelLearn/fuel/app/views/users/view.php
    Creating view: /var/www/html/fuelLearn/fuel/app/views/users/create.php
    Creating view: /var/www/html/fuelLearn/fuel/app/views/users/edit.php
    Creating view: /var/www/html/fuelLearn/fuel/app/views/users/_form.php
    Creating view: /var/www/html/fuelLearn/fuel/app/views/template.php

$~: oil r migrate

After that the system can't find the Model_User class, probably becaouse of the wrong model name.

**Comment by cbabos** [comment]
Sorry for the reedit, removed a fake bug.

**Comment by BetaBug** [comment]
It seems the Class name in the model is plural. Change the class name to singular like the file name is and it worked fine.

**Comment by philsturgeon** [comment]
You are supposed to create scaffolding on an entity, so "user" would work. The migration is plural, the table name is plural as is the controller, but the scaffold in general should be singular.
