### ISSUE TITLE
template.php location

### ISSUE THREAD

**Issue by merdj** [fuel/oil#37]
Hello,

first of all, thanks for a great framework

now this is my issue

when I issue the command
php oil g scaffold [model] [fields..n]

the above will create [model] including a template.php which is found in view

but question is
can we possibly move template.php to [model]/template.php?

my reason is, what if i want to generate or create all my models?

hope this is clear to all,,,

thanks

**Comment by dhrrgn** [comment]
You can specify the template to use per-controller.  In your controller do this:

`protecter $template = 'path/to/template';`

**Comment by jschreuder** [comment]
Also: the template isn't model specific, it's the same basic template for all your models. Thus there's no conflict by not putting that in the model directory.

**Comment by merdj** [comment]
hello,

thank you so much now it is working.

honestly, i just finish one project in Kohana here in the office, but after reviewing FuelPHP, i dumped Kohana and moved immediately to FuelPHP.

Honestly, I like Fuel comparing to other framework.

God bless you all
