### ISSUE TITLE
Option to make scaffolding non-plural

### ISSUE THREAD

**Issue by arbme** [fuel/oil#50]
Currently the scaffolding makes the model name plural for migration, controller and views. 

E.g.

$ php oil g scaffold monkey name:string description:text
    Created model: APPPATH/classes/model/monkey.php
    Created migration: APPPATH/migrations/003_create_monkeys.php
    Created controller: APPPATH/classes/controller/monkeys.php
    Created view: APPPATH/views/monkeys/index.php
    Created view: APPPATH/views/monkeys/view.php
    Created view: APPPATH/views/monkeys/create.php
    Created view: APPPATH/views/monkeys/edit.php
    Created view: APPPATH/views/monkeys/_form.php

Could we have a option to make it non-plural.

E.g.

$ php oil g scaffold monkey name:string description:text
    Created model: APPPATH/classes/model/monkey.php
    Created migration: APPPATH/migrations/003_create_monkey.php
    Created controller: APPPATH/classes/controller/monkey.php
    Created view: APPPATH/views/monkey/index.php
    Created view: APPPATH/views/monkey/view.php
    Created view: APPPATH/views/monkey/create.php
    Created view: APPPATH/views/monkey/edit.php
    Created view: APPPATH/views/monkey/_form.php

**Comment by frankdejonge** [comment]
Fixed in 8d24110
