### ISSUE TITLE
When i creating controller using oil i have some error 

### ISSUE THREAD

**Issue by purwandi** [fuel/oil#53]
Purwandis-MacBook-Pro:fuel purwandi$ php oil g controller user index login logout
Warning - file_get_contents(/Volumes/Storage/www/fuel/lib/fuel/packages/oil/views/default/template.php): failed to open stream: No such file or directory in PKGPATH/oil/classes/generate.php on line 275
    Creating view: /Volumes/Storage/www/fuel/app/views/template.php
    Creating view: /Volumes/Storage/www/fuel/app/views/user/index.php
    Creating view: /Volumes/Storage/www/fuel/app/views/user/login.php
    Creating view: /Volumes/Storage/www/fuel/app/views/user/logout.php
    Creating controller: /Volumes/Storage/www/fuel/app/classes/controller/user.php

**Comment by WanWizard** [comment]
This is a bug, views now depend on either the Crud model or the ORM model. @philsturgeon?

**Comment by philsturgeon** [comment]
Yes indeed. default is no longer the name of a template, it's either orm or crud. When the change was made it looks like this was never updated.

**Comment by purwandi** [comment]
So on line 275 can we use /orm/template.php or /crud/template.php on views

**Comment by philsturgeon** [comment]
Woah really?! ;-)

This is fixed here: e5b5b98ecd75a8177e538db993a12b610a10d2c7
