### ISSUE TITLE
--no-timestamp Still Creates Fields in Migration

### ISSUE THREAD

**Issue by knudpotente** [fuel/oil#55]
Using the "--no-timestamp'' option for generating models (and for scaffolding) still generates 'created_at' and 'updated_at' fields in the migration file. To reproduce:

```
oil g model monkey name:string description:string --orm --no-timestamp
```

The model file is produced correctly, without the time observers. 

The migration file, however, contains:

``` php
<?php

namespace Fuel\Migrations;

class Create_monkeys {

    public function up()
    {
        \DBUtil::create_table('monkeys', array(
            'id' => array('constraint' => 11, 'type' => 'int', 'auto_increment' => true),
            'name' => array('constraint' => 255, 'type' => 'varchar'),
            'description' => array('constraint' => 255, 'type' => 'varchar'),
            'created_at' => array('constraint' => 11, 'type' => 'int'),
            'updated_at' => array('constraint' => 11, 'type' => 'int'),
        ), array('id'));
    }

    public function down()
    {
        \DBUtil::drop_table('monkeys');
    }
}
```

It seems that the 'created_at' and 'updated_at' fields are still being included. This happens also when scaffolding.

**Comment by crynobone** [comment]
We have an inconsistency with no-timestamp,

oil generate model and scaffold use `--no-timestamp`

oil generate migration use `--no-timestamps`

Fuel Documentation use `--no-timestamp`
