### ISSUE TITLE
Inexistent "rename_field" Magic Migration

### ISSUE THREAD

**Issue by knudpotente** [fuel/oil#62]
The documentation mentions the existence of the following 'magic migration':

```
$ php oil generate migration rename_field_name_to_username
```

There does not seem to be any further documentation, and no example of how this is supposed to work - ie., if I have 2 tables with the same field name, how is the migration going to know which field (from which table) I'm trying to rename?

I have tried using the command, but only get errors:

```
knud$ oil g migration rename_field_salary1_to_salary999
Error - Database method Fuel\Core\Database_PDO_Connection::list_columns is not supported by
Fuel\Core\Database_PDO_Connection in COREPATH/classes/database/pdo/connection.php on line 191
```

**Comment by arbme** [comment]
@knudpotente you have missed off "in_db", but it still doesnt work.

E.g.

```
php oil generate migration rename_field_user_to_username_in_test
```

I have used the following and get the name error as knudpotente.

```
php oil generate migration rename_field_user_to_username_in_test
```

I have noticed when you use rename table you can't have a name containing more then one underscore, is this the case for rename_field. 

Would the following work with multiple underscores? If it doesn't please can be have this feature as some applications use long table/field names that sometimes contain prefixes.

```
php oil generate migration rename_field_user_to_user_details_in_test
php oil generate migration rename_field_user_details_to_user_profile_details_in_test
```

Thanks

**Comment by WanWizard** [comment]
The error here has nothing to do with Oil, but with the fact that the PDO driver doesn't support the list_columns() method, which is required for migration commands.

So it's not Oil that needs to be fixed, it's the PDO DB driver...

**Comment by WanWizard** [comment]
Marking this as invalid as it is a fuel/core issue, not an oil issue.
