### ISSUE TITLE
Form validation in Scaffolding

### ISSUE THREAD

**Issue by philsturgeon** [fuel/oil#9]
Yes please.

**Comment by LimeBlast** [comment]
Is there some way to 'like' this - because this is something I'd be keen on seeing :)

**Comment by philsturgeon** [comment]
TheWorldOfDan: I'm pretty confident you could do it if you gave it a try, you should be able to copy the majority of what I've done already.

I was planning to do this as I was using the MongoDB class that is now part of the core, but since then I have switched to using a MongoDB ODM so I have no personal interest in this feature. If you (or somebody else) would like to do it then... cool.

**Comment by okhayat** [comment]
+1 this would be great

**Comment by philsturgeon** [comment]
i will give advice on the approach or feedback on the implementation once a pull request comes in, but I do not have the time to play with this. I'd rather focus on Cells for 1.1 launch. Can anyone else tweak this?

**Comment by okhayat** [comment]
Would adding the validation to the controller and view be enough? Something like:
// create & edit action
if (Input::method() == 'POST')
{
    $val = Validation::forge();
    $val->add_field('name', 'Name', 'required');
    if ($val->run())
    {
    ...
    }
}
// _form.php
<?php if ($errors = Validation::instance()->show_errors()): ?>

<div class="alert-message block-message error">
<?php echo $errors ?>
</div>

<?php endif ?>
The add_field has a single 'required' rule for all fields without checking the field type, or size or anything else.

**Comment by philsturgeon** [comment]
Yep that sort of thing! 

So if its an int/integer field make sure its numeric, if its a string make sure it matches the constraint length, etc.

**Comment by dbpolito** [comment]
https://github.com/fuel/oil/pull/80

**Comment by philsturgeon** [comment]
Good man, I'll close this so we can continue over there.
