### ISSUE TITLE
alert-message error and list color

### ISSUE THREAD

**Issue by crynobone** [fuel/oil#95]
> Hi
> 
> When using scaffolding, error messages are very difficult to read because of the grey text-color (ul > li) into the alert-message error div http://goo.gl/8ngXb
> 
> Thanks,

originally reported by : @jacky672

**Comment by aranw** [comment]
That probably wants updating to the proper use of error `div` rather than altering the `text-color`. 

Bootstraps error div normally expects a `p` element rather than a list.

**Comment by WanWizard** [comment]
@crynobone @aranw can someone code up an example of what it should be so it can be part of v1.2?

**Comment by aranw** [comment]
Hmmm I can't remember this exactly and the image has gone if @crynobone can re-add the original image or replicate the original problem I could get a example of how the code should be.

**Comment by WanWizard** [comment]
Was this about the errors displayed in red (which is very dark against a black background)?

**Comment by WanWizard** [comment]
Closed due to lack of response.
